"""Office tools: functions + JSON Schema for Function Calling"""

TOOLS_SCHEMA = [
    {
        "type": "function",
        "function": {
            "name": "generate_weekly_report",
            "description": "Generate a formatted weekly report based on user's work description",
            "parameters": {
                "type": "object",
                "properties": {
                    "content": {"type": "string", "description": "Work content for the week"},
                    "week_range": {"type": "string", "description": "e.g. 'July 14-July 18'"}
                },
                "required": ["content"]
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "summarize_meeting",
            "description": "Organize meeting notes into structured minutes with action items",
            "parameters": {
                "type": "object",
                "properties": {
                    "notes": {"type": "string", "description": "Raw meeting notes"}
                },
                "required": ["notes"]
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "process_excel",
            "description": "Process Excel data: sum, average, filter, sort",
            "parameters": {
                "type": "object",
                "properties": {
                    "action": {"type": "string", "enum": ["sum", "average", "filter", "sort"], "description": "Operation to perform"},
                    "data_description": {"type": "string", "description": "Description of the data"},
                    "numbers": {"type": "string", "description": "Comma-separated numbers, e.g. '100,200,300'"}
                },
                "required": ["action", "data_description"]
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "send_notification",
            "description": "Send email notification to a person or department",
            "parameters": {
                "type": "object",
                "properties": {
                    "recipient": {"type": "string", "description": "Recipient name or email"},
                    "message": {"type": "string", "description": "Notification content"},
                    "priority": {"type": "string", "enum": ["normal", "urgent"], "description": "Priority level"}
                },
                "required": ["recipient", "message"]
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "search_knowledge",
            "description": "Search internal knowledge base for policies and procedures",
            "parameters": {
                "type": "object",
                "properties": {
                    "query": {"type": "string", "description": "Search query"}
                },
                "required": ["query"]
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "search_contacts",
            "description": "Search the company contact list by name to find email and department",
            "parameters": {
                "type": "object",
                "properties": {
                    "name": {"type": "string", "description": "Name to search for"}
                },
                "required": ["name"]
            }
        }
    }
]


def generate_weekly_report(content: str, week_range: str = "This week") -> str:
    return f"""## Weekly Report ({week_range})

### Work Completed
{content}

### Next Week Plan
(Please add as needed)

---
*Generated by AI Office Agent*"""


def summarize_meeting(notes: str) -> str:
    return f"""## Meeting Minutes

### Raw Notes
{notes}

---
*Extract: attendees, topics, decisions, action items*"""


def process_excel(action: str, data_description: str, numbers: str = "") -> str:
    if not numbers:
        return f"Action: {action}\nData: {data_description}\nResult: Please provide numbers."
    nums = [float(n.strip()) for n in numbers.split(",") if n.strip()]
    if not nums:
        return f"Action: {action}\nData: {data_description}\nResult: No valid numbers."
    if action == "sum":
        return f"Sum of {data_description}: {sum(nums)}"
    elif action == "average":
        return f"Average of {data_description}: {sum(nums)/len(nums):.2f}"
    elif action == "sort":
        return f"Sorted {data_description}: {sorted(nums)}"
    else:
        return f"Action: {action} on {data_description}: {nums}"


async def send_notification(recipient: str, message: str, priority: str = "normal") -> str:
    import os, smtplib, asyncio
    from email.mime.text import MIMEText

    try:
        from backend.database import SessionLocal
        db = SessionLocal()
        rows = db.execute("SELECT name, email FROM contacts WHERE name LIKE ?", (f"%{recipient}%",)).fetchall()
        db.close()
        for name, email in rows:
            if name in recipient:
                recipient = email
                break
    except:
        pass

    try:
        smtp_host = os.getenv("SMTP_HOST", "smtp.qq.com")
        smtp_user = os.getenv("SMTP_USER", "")
        smtp_pass = os.getenv("SMTP_PASS", "")
        if not smtp_user or not smtp_pass:
            return f"SMTP not configured"

        msg = MIMEText(f"Hello,\n\n{message}\n\n---\nAI Office Agent\nTo: {recipient}\nPriority: {priority}", "plain", "utf-8")
        msg["From"] = smtp_user
        msg["To"] = smtp_user
        msg["Subject"] = f"{'[URGENT] ' if priority == 'urgent' else ''}Notification: {recipient}"

        def _send():
            server = smtplib.SMTP_SSL(smtp_host, 465, timeout=10)
            server.login(smtp_user, smtp_pass)
            server.send_message(msg)
            server.quit()

        await asyncio.get_event_loop().run_in_executor(None, _send)
        return f"Email sent to {recipient}: {message}"
    except Exception as e:
        return f"Email failed: {str(e)}"


def search_knowledge(query: str) -> str:
    """Search internal knowledge base including uploaded documents"""
    import sqlite3, os
    db_path = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "office.db")
    conn = sqlite3.connect(db_path)
    print(f"[search_knowledge] query: {query}")
    rows = conn.execute(
        "SELECT title, content FROM documents WHERE content LIKE ? OR title LIKE ? LIMIT 5",
        (f"%{query}%", f"%{query}%")
    ).fetchall()
    conn.close()
    
    if rows:
        result = "Knowledge base results:\n"
        for title, content in rows:
            result += f"\n--- {title} ---\n{content[:500]}\n"
        return result
    
    # Fallback to hardcoded knowledge
    knowledge_base = {
        "leave": "Leave process: 1. Submit in OA -> 2. Manager approval -> 3. HR filing for >3 days. Annual leave: 15 days.",
        "reimbursement": "Reimbursement: Submit receipts -> OA form -> Dept approval -> Finance -> Payment (5 business days).",
        "weekly": "Weekly report deadline: Every Friday 17:00.",
        "overtime": "Overtime: Apply in OA. Pay: 1.5x weekday, 2x weekend, 3x holiday.",
    }
    for key, answer in knowledge_base.items():
        if key in query.lower():
            return f"Knowledge Base:\n\n{answer}"
    return f"No results found for '{query}'."

def search_contacts(name: str) -> str:
    try:
        import sqlite3, os
        db_path = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "office.db")
        conn = sqlite3.connect(db_path)
        rows = conn.execute("SELECT name, email, department FROM contacts WHERE name LIKE ?", (f"%{name}%",)).fetchall()
        conn.close()
        if not rows:
            return f"No contacts found for '{name}'."
        result = "Contacts found:\n"
        for r in rows:
            result += f"- {r[0]} | {r[1]} | {r[2]}\n"
        return result
    except Exception as e:
        return f"Search failed: {str(e)}"